src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cet email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre nom")
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Le nom doit comporter au moins {{ limit }} caractères",
     *      maxMessage = "Le nom du titre ne peut pas dépasser {{ limit }} caractères"
     * )
     */
    private $lastName;

    /**
     * @ORM\ManyToOne(targetEntity=Theme::class, inversedBy="users")
     */
    private $Theme;

    /**
     * @ORM\OneToMany(targetEntity=Tasklist::class, mappedBy="user")
     */
    private $tasklists;

    public function __construct()
    {
        $this->tasklists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->Theme;
    }

    public function setTheme(?Theme $Theme): self
    {
        $this->Theme = $Theme;

        return $this;
    }

    /**
     * @return Collection<int, Tasklist>
     */
    public function getTasklists(): Collection
    {
        return $this->tasklists;
    }

    public function addTasklist(Tasklist $tasklist): self
    {
        if (!$this->tasklists->contains($tasklist)) {
            $this->tasklists[] = $tasklist;
            $tasklist->setUser($this);
        }

        return $this;
    }

    public function removeTasklist(Tasklist $tasklist): self
    {
        if ($this->tasklists->removeElement($tasklist)) {
            // set the owning side to null (unless already changed)
            if ($tasklist->getUser() === $this) {
                $tasklist->setUser(null);
            }
        }

        return $this;
    }

    public function getActiveTasklists() {
        return $this->getTasklists()->filter(function(Tasklist $tasklist) {
            return $tasklist->getArchivedAt() === null;
        });
    }

    public function getArchivedTasklists() {
        return $this->getTasklists()->filter(function(Tasklist $tasklist) {
            return $tasklist->getArchivedAt();
        });
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">
        <link rel="manifest" href="{{ asset('site.webmanifest') }}">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
        {% if app.user and app.user.theme %}
            <link rel="stylesheet" href="{{'../../assets/css/' ~ app.user.theme.name ~ '/bootstrap.min.css'}}">
        {% else %}
            <link rel="stylesheet" href="../../assets/css/sandstone/bootstrap.min.css">
        {% endif %}
        <link rel="stylesheet" href="../../assets/css/style.css">
           {# {{ encore_entry_link_tags('app') }} #} 
        {% endblock %}
    </head>
    <body>

        {% if app.user %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler mx-2" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                    <ul class="navbar-nav mx-2">
                        <li class="nav-item">
                            <a class="nav-link {% if app.request.get('_route') is same as 'tasklists' %} active {% endif %}" href="{{ path('tasklists') }}">Listes actives ({{ app.user.getActiveTasklists|length }})</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if app.request.get('_route') is same as 'archived_tasklists' %} active {% endif %}" href="{{ path('archived_tasklists') }}">Listes archivées ({{ app.user.getArchivedTasklists|length }})</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if app.request.get('_route') is same as 'change_theme' %} active {% endif %}" href="{{ path('change_theme') }}">Changer de thème</a>
                        </li>
                    </ul>
                    <div class="d-flex align-items-center flex-wrap mx-2">
                        <p class="greeting text-secondary">Bonjour, {{ app.user.firstName }}</p>
                        <a href="{{ path('logout') }}" class="btn btn-secondary" type="submit">Se déconnecter</a>
                    </div>
                </div>
            </nav>
        {% else %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
                <button class="btn btn-primary mx-2">
                    {% if app.request.get('_route') is same as 'login' %}
                        <a href="{{ path('app_register') }}">Créer un compte</a>
                    {% elseif app.request.get('_route') is same as 'app_register' %}
                        <a href="{{ path('login') }}">Se Connecter</a>
                    {% endif %}
                </button>
            </nav>
        {% endif %}
        <div class="container mt-5">
            <!-- Flash messages -->
            {% for message in app.flashes('success') %}
                <div class="badge bg-success text-white mb-3">{{ message }}</div>
            {% endfor %}
            {% block body %}{% endblock %}
        </div>

        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
            {# {{ encore_entry_script_tags('app') }} #}
        {% endblock %}
    </body>
</html>